version: 2.0
jobs:
  "node-6":
    working_directory: ~/cra-6
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: |
        npm test
        npm run build
  "node-8":
    working_directory: ~/cra-8
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: |
        npm test
        npm run build

workflows:
  version: 2
  build:
    jobs:
      - "node-6"
      - "node-8"
