version: 2.0

aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "package.json" }}

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}

jobs:
  "node-6":
    working_directory: ~/cra-6
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: node --version
      - run: npm --version
      - run: npm install
      - save-cache: *save-cache
      - run: |
        npm test
        npm run build
  "node-8":
    working_directory: ~/cra-8
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: node --version
      - run: npm --version
      - run: npm install
      - save-cache: *save-cache
      - run: |
        npm test
        npm run build

workflows:
  version: 2
  build:
    jobs:
      - "node-6"
      - "node-8"
